set_property PACKAGE_PIN C13 [get_ports {mdio_mdc                    }] 
set_property PACKAGE_PIN C14 [get_ports {mdio_mdio_io            }] 
set_property PACKAGE_PIN H23 [get_ports {phy_reset_n[0]                   }] 
set_property PACKAGE_PIN D10 [get_ports {rgmii_rxc                  }] 
set_property PACKAGE_PIN C10 [get_ports {rgmii_rx_ctl            }] 
set_property PACKAGE_PIN C12 [get_ports {rgmii_rd[0]              }] 
set_property PACKAGE_PIN D11 [get_ports {rgmii_rd[1]              }] 
set_property PACKAGE_PIN A14 [get_ports {rgmii_rd[2]              }] 
set_property PACKAGE_PIN B13 [get_ports {rgmii_rd[3]              }] 
set_property PACKAGE_PIN A13 [get_ports {rgmii_txc                  }] 
set_property PACKAGE_PIN B12 [get_ports {rgmii_tx_ctl            }] 
set_property PACKAGE_PIN A11 [get_ports {rgmii_td[0]              }] 
set_property PACKAGE_PIN B11 [get_ports {rgmii_td[1]              }] 
set_property PACKAGE_PIN A10 [get_ports {rgmii_td[2]              }] 
set_property PACKAGE_PIN B10 [get_ports {rgmii_td[3]              }] 
 
set_property IOSTANDARD LVCMOS33 [get_ports {mdio_mdc                    }] 
set_property IOSTANDARD LVCMOS33 [get_ports {mdio_mdio_io            }] 
set_property IOSTANDARD LVCMOS15 [get_ports {phy_reset_n[0]                  }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxc                  }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rx_ctl            }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[0]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[1]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[2]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[3]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txc                  }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_ctl            }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[0]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[1]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[2]              }] 
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[3]              }] 

create_clock -period 8.000 -name rgmii_rxc [get_ports rgmii_rxc]



